version: "3.7"
services:
  webhook:
    image: "dontjustadream/fastify-webhook:latest"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webhook
    restart: on-failure
    expose:
      - "3000"
    ports:
      - "3000:3000"
