name: Vercel Production Deployment
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      vercel_token: ${{ steps.vercel_token.outputs.defined }}
    steps:
      - name: Check for Secret availability
        id: vercel_token
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.VERCEL_TOKEN }}" != '' ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi
  Deploy-Production:
    runs-on: ubuntu-latest
       needs: [check-secret]
        if: needs.check-secret.outputs.vercel_token == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
